"""
agents/execution_agent.py — Execution & Verification Agent
============================================================

Why this agent exists
---------------------
The Execution Agent closes the autonomous rerouting loop.  After the
Decision Agent selects a route, someone or something must:
1.  "Execute" the reroute (submit to carrier booking system)
2.  Notify all stakeholders
3.  Generate a documented record of the resolution

In this simulated system, step 1 is deterministic (a confirmation
number is generated).  Steps 2 and 3 use the LLM tool loop so that
the agent must reason about what to pass to each tool — this is the
evaluation surface for tool-calling accuracy in the final stage.

State fields read
-----------------
    selected_route        : The route chosen by Decision Agent
    telemetry_alert       : Shipment context for notification and report
    rerouting_constraints : For cost context
    trajectory            : To extract metrics for the report
    run_id, model_name, step_count
    total_tool_calls, successful_tool_calls, total_cost_usd

State fields written
--------------------
    execution_result  : ExecutionResult (replace semantics)
    execution_status  : "completed" | "failed" | "escalated"
    step_count        : incremented
    trajectory        : one snapshot appended
    (evaluation metadata)

Tools used
----------
    send_reroute_notification  — notifies all stakeholders
    generate_execution_report  — documents the resolution

(from tools.EXECUTION_TOOLS — exactly two tools)

Reroute execution (simulated)
-----------------------------
In a real system, this agent would call a carrier booking API and
receive a confirmation number.  In our simulated environment, the
``_simulate_reroute_execution`` method generates a realistic
confirmation number deterministically from the route details.
This is the ONLY non-LLM action in this agent — everything else
(notification, report) goes through the LLM tool loop.

Prompt design rationale
-----------------------
The system prompt provides the full reroute result (confirmation
number, carrier, route, ETA, cost) and instructs the agent to:
1.  Call ``send_reroute_notification`` with the correct parameters.
2.  Call ``generate_execution_report`` with the full metric set.
3.  Confirm the actions taken in a JSON summary.

The report tool requires many numeric arguments (total_steps,
total_tool_calls, etc.) — the prompt injects these directly so the
LLM doesn't need to invent them.  This is a deliberate design choice:
metrics that can be computed by Python SHOULD be computed by Python and
passed to the LLM, not generated by the LLM.  This makes the report
data accurate and auditable.
"""

from __future__ import annotations

import hashlib
import time
import uuid
from datetime import datetime, timezone
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from agents.base_agent import BaseAgent
from config.settings import AppSettings
from graphs.state import ExecutionResult, GraphState, SelectedRoute, ShipmentAlert, ToolCallRecord
from tools import EXECUTION_TOOLS

# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """You are the Execution & Verification Agent in an autonomous logistics rerouting system.

YOUR ROLE: Confirm the reroute execution, notify stakeholders, and generate the final incident report.

AVAILABLE TOOLS:
- send_reroute_notification  — dispatch notifications to all stakeholders
- generate_execution_report  — produce the structured incident report

THE REROUTE HAS BEEN EXECUTED. Details:
  Shipment ID          : {shipment_id}
  Customer ID          : {customer_id}
  Original Carrier     : {original_carrier}
  New Carrier          : {new_carrier}
  New Route ID         : {new_route_id}
  Transit Mode         : {transit_mode}
  New ETA (hours)      : {eta_hours:.0f}
  New Cost (USD)       : ${new_cost:,.2f}
  Confirmation Number  : {confirmation_number}
  Execution Status     : {exec_status}

DELAY CONTEXT:
  Delay Reason         : {delay_reason}
  Priority             : {priority}

AGENT RUN METRICS (inject these into generate_execution_report):
  Run ID               : {run_id}
  Model                : {model_name}
  Total Steps          : {total_steps}
  Total Tool Calls     : {total_tool_calls}
  Successful Calls     : {successful_calls}
  LLM Cost (USD)       : ${llm_cost:.6f}
  Errors               : {error_count}

INSTRUCTIONS:
Step 1: Call send_reroute_notification with the reroute details above.
Step 2: Call generate_execution_report with ALL the metrics above.
Step 3: Respond with a JSON confirmation summary.

After all tool calls, respond ONLY with this JSON (no markdown):
{{
  "reasoning": "<brief confirmation of actions taken>",
  "notification_sent": <true|false>,
  "report_generated": <true|false>,
  "final_status": "completed|failed",
  "summary": "<one sentence ops summary>"
}}"""


# ---------------------------------------------------------------------------
# ExecutionAgent
# ---------------------------------------------------------------------------


class ExecutionAgent(BaseAgent):
    """
    Fourth and final node in the logistics rerouting graph.

    Simulates reroute execution, dispatches stakeholder notifications,
    and generates the final incident report.
    """

    agent_name: str = "execution"

    def __init__(self, settings: AppSettings | None = None) -> None:
        super().__init__(settings)

    def _simulate_reroute_execution(
        self,
        route: SelectedRoute,
        alert: ShipmentAlert,
    ) -> tuple[bool, str]:
        """
        Simulate submitting the reroute to the carrier booking system.

        In production this would call the carrier's API.  Here we
        generate a deterministic confirmation number from the route
        details so that test runs produce the same confirmation number
        for the same inputs (useful for test assertions).

        Returns
        -------
        (success, confirmation_number)
            Always succeeds in the simulation unless the route's
            confidence score is below 0.5 (used to test failure paths).
        """
        # Deterministic confirmation number from route + shipment
        digest = hashlib.md5(
            f"{route.carrier_id}{route.route_id}{alert.shipment_id}".encode()
        ).hexdigest()[:8].upper()
        confirmation = f"BK-{route.carrier_id.replace('CARRIER-', '')}-{digest}"

        # Simulate failure only for very low confidence routes
        success = route.confidence_score >= 0.50

        if success:
            self.logger.info(
                "reroute_submitted",
                agent=self.agent_name,
                carrier=route.carrier_id,
                confirmation=confirmation,
                simulated=True,
            )
        else:
            self.logger.warning(
                "reroute_submission_failed",
                agent=self.agent_name,
                carrier=route.carrier_id,
                confidence=route.confidence_score,
            )

        return success, confirmation if success else ""

    def _build_prompts(
        self,
        alert: ShipmentAlert,
        route: SelectedRoute,
        confirmation: str,
        exec_status: str,
        run_id: str,
        model_name: str,
        cumulative_metrics: dict[str, Any],
    ) -> tuple[str, str]:
        """Build (system_prompt, human_prompt) injecting all execution context."""
        system = _SYSTEM_PROMPT.format(
            shipment_id=alert.shipment_id,
            customer_id=alert.customer_id,
            original_carrier=alert.current_carrier,
            new_carrier=route.carrier,
            new_route_id=route.route_id,
            transit_mode=route.transit_mode,
            eta_hours=route.eta_hours,
            new_cost=route.estimated_cost_usd,
            confirmation_number=confirmation or "PENDING",
            exec_status=exec_status,
            delay_reason=alert.delay_reason,
            priority=alert.priority,
            run_id=run_id,
            model_name=model_name,
            total_steps=cumulative_metrics.get("total_steps", 4),
            total_tool_calls=cumulative_metrics.get("total_tool_calls", 0),
            successful_calls=cumulative_metrics.get("successful_tool_calls", 0),
            llm_cost=cumulative_metrics.get("total_cost_usd", 0.0),
            error_count=cumulative_metrics.get("error_count", 0),
        )
        human = (
            f"Execute the stakeholder notification and generate the incident "
            f"report for shipment {alert.shipment_id}. "
            f"Use the confirmation number {confirmation or 'N/A'}. "
            f"Complete both tool calls before responding."
        )
        return system, human

    def _build_execution_result(
        self,
        route: SelectedRoute,
        alert: ShipmentAlert,
        success: bool,
        confirmation: str,
        tool_records: list[ToolCallRecord],
        retry_count: int,
        error_message: str | None = None,
    ) -> ExecutionResult:
        """Build the ``ExecutionResult`` from execution + tool call outcomes."""
        # Extract notification info from tool records
        notification_sent = False
        notification_recipients: list[str] = []
        for record in tool_records:
            if record.tool_name == "send_reroute_notification" and record.success:
                result = record.raw_result or {}
                notification_sent = result.get("success", False)
                notification_recipients = result.get("recipients", [])

        return ExecutionResult(
            success=success,
            confirmation_number=confirmation or None,
            carrier=route.carrier,
            route_id=route.route_id,
            final_cost_usd=route.estimated_cost_usd,
            final_eta_hours=route.eta_hours,
            notification_sent=notification_sent,
            notification_recipients=notification_recipients,
            executed_at_utc=datetime.now(timezone.utc),
            retry_count=retry_count,
            error_message=error_message,
            error_type="ExecutionFailure" if (not success and error_message) else None,
        )

    def run(self, state: GraphState) -> dict[str, Any]:
        """
        Execute the Execution Agent.

        Simulates reroute submission, runs the notification + report
        tool loop, and produces the final ``ExecutionResult``.
        """
        agent_start = time.perf_counter()
        step_index = state.get("step_count", 0)
        run_id = state.get("run_id", "unknown")
        model_name = state.get("model_name", self.settings.closed_source_model)
        alert: ShipmentAlert = state["telemetry_alert"]
        route: SelectedRoute | None = state.get("selected_route")
        retry_count: int = state.get("retry_count", 0)

        self.logger.info(
            "agent_start",
            agent=self.agent_name,
            step=step_index,
            model=model_name,
            run_id=run_id,
            carrier=route.carrier_id if route else "none",
        )

        if route is None:
            # Should not happen if the graph is wired correctly
            self.logger.error(
                "no_route_to_execute",
                agent=self.agent_name,
                run_id=run_id,
            )
            return {
                "execution_status": "failed",
                "execution_result": None,
                "step_count": step_index + 1,
                "trajectory": [],
                "error_message": "Execution Agent received no SelectedRoute.",
                "error_history": ["Execution Agent received no SelectedRoute."],
            }

        # Cumulative metrics (read-only from state for report generation)
        cumulative = {
            "total_steps": step_index + 1,
            "total_tool_calls": state.get("total_tool_calls", 0),
            "successful_tool_calls": state.get("successful_tool_calls", 0),
            "total_cost_usd": state.get("total_cost_usd", 0.0),
            "error_count": len(state.get("error_history", [])),
        }

        error_info: dict[str, str] | None = None
        tool_records: list[ToolCallRecord] = []
        prompt_tokens = 0
        completion_tokens = 0
        reasoning_trace = ""
        execution_result: ExecutionResult | None = None
        final_status: str = "failed"

        try:
            # Step 1: Simulate reroute submission (deterministic, no LLM needed)
            submitted_ok, confirmation = self._simulate_reroute_execution(route, alert)
            exec_status = "completed" if submitted_ok else "failed"

            # Step 2: LLM tool loop for notification + report
            llm = self._build_llm(model_name)
            system_prompt, human_prompt = self._build_prompts(
                alert=alert,
                route=route,
                confirmation=confirmation,
                exec_status=exec_status,
                run_id=run_id,
                model_name=model_name,
                cumulative_metrics=cumulative,
            )
            messages = [
                SystemMessage(content=system_prompt),
                HumanMessage(content=human_prompt),
            ]

            final_response, tool_records, total_tokens = self._invoke_with_tool_loop(
                llm=llm,
                tools=EXECUTION_TOOLS,
                messages=messages,
                max_iterations=4,
            )

            prompt_tokens = total_tokens["prompt"]
            completion_tokens = total_tokens["completion"]

            parsed = self._parse_json(final_response.content or "")
            reasoning_trace = parsed.get("reasoning", final_response.content[:500])
            final_status = parsed.get("final_status", exec_status)

            execution_result = self._build_execution_result(
                route=route,
                alert=alert,
                success=submitted_ok,
                confirmation=confirmation,
                tool_records=tool_records,
                retry_count=retry_count,
            )

            self.logger.info(
                "agent_success",
                agent=self.agent_name,
                status=final_status,
                confirmation=confirmation,
                notification_sent=execution_result.notification_sent,
            )

        except Exception as exc:
            error_info = {"type": type(exc).__name__, "message": str(exc)}
            final_status = "failed"
            execution_result = ExecutionResult(
                success=False,
                confirmation_number=None,
                carrier=route.carrier,
                route_id=route.route_id,
                final_cost_usd=route.estimated_cost_usd,
                final_eta_hours=route.eta_hours,
                retry_count=retry_count,
                error_message=str(exc),
                error_type=type(exc).__name__,
            )
            self.logger.exception(
                "agent_error",
                agent=self.agent_name,
                error=str(exc),
            )

        latency_ms = (time.perf_counter() - agent_start) * 1000.0
        successful_calls = sum(1 for r in tool_records if r.success)
        cost = self._estimate_cost(model_name, prompt_tokens, completion_tokens)

        snapshot = self._make_snapshot(
            run_id=run_id,
            model_name=model_name,
            step_index=step_index,
            input_summary={
                "carrier": route.carrier_id,
                "route_id": route.route_id,
                "confidence": route.confidence_score,
            },
            output_summary={
                "execution_status": final_status,
                "success": execution_result.success if execution_result else False,
                "confirmation": execution_result.confirmation_number if execution_result else None,
                "notification_sent": execution_result.notification_sent if execution_result else False,
            },
            tool_records=tool_records,
            reasoning_trace=reasoning_trace,
            latency_ms=latency_ms,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            error_info=error_info,
        )

        self.logger.info(
            "agent_complete",
            agent=self.agent_name,
            latency_ms=round(latency_ms, 1),
            status=final_status,
            cost_usd=round(cost, 6),
        )

        return {
            "execution_result": execution_result,
            "execution_status": final_status,
            "step_count": step_index + 1,
            "trajectory": [snapshot],
            "total_tool_calls": len(tool_records),
            "successful_tool_calls": successful_calls,
            "total_prompt_tokens": prompt_tokens,
            "total_completion_tokens": completion_tokens,
            "total_cost_usd": cost,
            "error_message": error_info["message"] if error_info else None,
            "error_history": [error_info["message"]] if error_info else [],
        }
